name: Debounce Validation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  debounce-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install requirements
        run: pip install -r tools/debounce_validation/requirements.txt

      - name: Run test suite
        run: python3 -m unittest discover -s tools/debounce_validation
